project: default

global:
  clusterConfigPath: infra/clusters/cluster-configs

source:
  repoURL: https://github.com/vramk23/infrapub.git
  targetRevision: main
  
destination:
  server: https://kubernetes.default.svc
  namespace: crossplane

syncPolicy:
  CreateNamespace: true
  automated:
    prune: true
    selfHeal: true

compositions:
  - name: aws-compositions
    path: infra/clusters/compositions/aws

clusters:
  - name: dev-eks
    defaultApps:
    - name: falco
      vaulesPath: infra/clusters/app-configs/dev-test/falco-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devfalco
      chart: falco
      targetRevision: "0.0.1"
    - name: kyverno
      vaulesPath: infra/clusters/app-configs/dev-test/kyverno-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devkyverno
      chart: kyverno
      targetRevision: "1.0.2"
    - name: prometheus
      vaulesPath: infra/clusters/app-configs/dev-test/prometheus-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devprometheus
      chart: kube-prometheus-stack
      targetRevision: "1.0.3"
    - name: promtail
      vaulesPath: infra/clusters/app-configs/dev-test/promtail-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devpromtail
      chart: promtail
      targetRevision: "1.0.0"
